name: Nightly Builds

on:
  schedule:
    - cron: '0 2 * * *' # Runs at 02:00 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  nightly_build:
    name: Build on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ['3.11']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix user Scripts missing from PATH
        if: matrix.os == 'windows-latest'
        run: |
          $ScriptsPath = python -c "import sysconfig,os; print(sysconfig.get_path('scripts'))"
          Add-Content $env:GITHUB_PATH $ScriptsPath

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install create-dmg glib gtk+3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install wheel helper
        run: uv pip install --system wheel

      - name: Install Python dependencies
        run: |
          uv pip install --system -r requirements.txt -r requirements-dev.txt

      - name: Fix pywin32
        if: matrix.os == 'windows-latest'
        run: |
          $ScriptsPath = python -c "import sysconfig,os; print(sysconfig.get_path('scripts'))"
          python "$ScriptsPath\pywin32_postinstall.py" -install

      - name: Build macOS DMG
        if: matrix.os == 'macos-latest'
        run: |
          version=$(cat VERSION_BASE)
          git_revision=$(git rev-parse --short HEAD)
          version_tag="${version}.${git_revision}.nightly"
          uv build;
          uv pip install ./dist/displaycal-${version}-*.whl --force-reinstall;
          python setup.py py2app
          build_folder=$(ls dist | grep -i py2app.macosx)
          ln -s /Applications "dist/${build_folder}/DisplayCAL-${version}/Applications"
          create-dmg --volname DisplayCAL-${version} dist/DisplayCAL-${version_tag}-macOS-arm64.dmg dist/$build_folder/DisplayCAL-${version}

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          $version = Get-Content VERSION_BASE
          $git_revision = git rev-parse --short HEAD
          $version_tag = "$version.$git_revision.nightly"
          python DisplayCAL\freeze.py
          $build_folder = Get-ChildItem dist\py2exe.*
          python setup.py inno
          $iss_file = Get-ChildItem dist\*.iss

      - name: Build Windows Installer
        if: matrix.os == 'windows-latest'
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: $iss_file

      - name: Update nightly release
        uses: eine/tip@master
        with:
          tag: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*.dmg dist/*.exe
